### ISSUE TITLE
Plugin fails on path.join for v.1 alpha

### ISSUE THREAD

**Issue by jfbon** [sindresorhus/gulp-ruby-sass#185]
This does not happen on 0.7.1. As soon as I downgraded, gulp runs fine.

```
[10:06:02] Using gulpfile /vagrant/www/wp-dev/frontend/wp-content/themes/bullet/gulpfile.js
[10:06:02] Starting 'sass'...
[10:06:02] 'sass' errored after 8.89 ms
[10:06:02] TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at module.exports (/vagrant/www/wp-dev/frontend/wp-content/themes/bullet/node_modules/gulp-ruby-sass/index.js:60:15)
    at Gulp.gulp.task.gulp.src.pipe.pipe.rename.suffix (/vagrant/www/wp-dev/frontend/wp-content/themes/bullet/gulpfile.js:17:9)
    at module.exports (/vagrant/www/wp-dev/frontend/wp-content/themes/bullet/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/vagrant/www/wp-dev/frontend/wp-content/themes/bullet/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/vagrant/www/wp-dev/frontend/wp-content/themes/bullet/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/vagrant/www/wp-dev/frontend/wp-content/themes/bullet/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
```

Here's my task, called with watch...
```
/**
 * Compile all CSS for the site
 */
gulp.task( 'sass', function() {
	gulp.src('assets/scss/app.scss')
		.pipe(sass())                                              // Compile sass
		.on('error', function (err) { console.log(err.message); }) // Handle sass errors
		.pipe(concat('styles.css'))                                // Concat all css
		.pipe(rename({suffix: '.min'}))                            // Rename it
		.pipe(minifycss())                                         // Minify the CSS
		.pipe(gulp.dest('assets/dist/'));                          // Set the destination to assets/css

	util.log(util.colors.yellow('Sass compiled & minified'))   // Output to terminal
});
```

**Comment by robwierzbowski** [comment]
Read the 1.0 documentation and recipes. gulp-ruby-sass replaces gulp.src.
