### ISSUE TITLE
Multiple destinations in loop fails

### ISSUE THREAD

**Issue by joeyhoer** [sindresorhus/gulp-ruby-sass#202]
A project I am working on requires a number of themes, compiled into different directories, which inherit from a master theme. When compiling a single directory, `gulp-ruby-sass` works fine, however mapping the output for each individual theme into it's own directory breaks. (Using `1.0.0-alpha`)

```
var gulp = require( 'gulp' ),
    sass = require( 'gulp-ruby-sass' ),
    fs = require('fs'),
    path = require('path');

var config = {
  default: 'default',
  skin_dir: 'skin/frontend/theme'
};

function getFolders(dir) {
    return fs.readdirSync(dir)
      .filter(function(file) {
        return fs.statSync(path.join(dir, file)).isDirectory();
      });
}

gulp.task('styles', function() {
    // Multiple values do not work
    var dirs = getFolders(config.skin_dir);
    // But a single value does work
    // var dirs = ['default'];
    var compile = dirs.map(function(dir){
        var theme_dir = config.skin_dir + '/' + dir;
        return sass( theme_dir + '/scss/style.scss',
            {
                sourcemap: true,
                loadPath: config.skin_dir + '/' + config.default + '/scss',
                style: 'expanded'
            })
            .on('error', function (err) {
              console.error('Error', err.message);
            })
            .pipe(gulp.dest( theme_dir + '/css' ));
    });
});

gulp.task('watch', function() {
    gulp.watch(config.skin_dir + '/**/*.scss', ['styles']);
});

gulp.task('default', ['styles', 'watch']);
```

The errors I get vary, which leads me to believe that this is a problem with synchronicity.

Is this the preferred way to accomplish this? If not, how should this be accomplished?

**Comment by robwierzbowski** [comment]
What are some of the errors? Remember to use the `container` option.

**Comment by joeyhoer** [comment]
A common error is:
```
fs.js:696
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/var/folders/5h/xcq6y2pn6_g3ccgwz4q8v3g80000gn/T/gulp-ruby-sass/style.css.map'
    at Object.fs.statSync (fs.js:696:18)
    at Object.<anonymous> (/www/node_modules/gulp-ruby-sass/index.js:158:12)
    at Object.immediate._onImmediate (timers.js:372:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by robwierzbowski** [comment]
Can you try adding `container: somestring` to options, where `somestring` is a var that's set per directory. Maybe use `forEach` instead of `map` and then use the `index`?

**Comment by joeyhoer** [comment]
@robwierzbowski `container` worked like a charm (facepalm) - thanks for your help!

**Comment by robwierzbowski** [comment]
No problem! Figured it was a race condition with container deletion.
