### ISSUE TITLE
Error ENOENT (Temp directory not available)

### ISSUE THREAD

**Issue by nikitabulatov** [sindresorhus/gulp-ruby-sass#272]
Error after compile. 
It repeated often but not always

``` bash
Use --trace for backtrace.
[09:22:32] 'sprsrc/scss/viewdir/company.scss' was changed
[09:22:32] Starting 'scss'...
[09:22:32] Finished 'scss' after 12 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/tmp/gulp-ruby-sass-fd0d152d5598759dcdb787d86a419e37a7bc4cc9f2ecbde6d8fa7566e4f76c68/main.css' at Error (native)
```

Here my sass options:

``` javascript
    sass: {
        sourcemap: argv.p ? false : true,
        style: argv.p ? 'compressed' : 'expanded',
        loadPath: './bower_components/'
    },
```

And gulp-task:

``` javascript
gulp.task('scss', function(){
    p.rubySass(c.src.scss + 'main.scss', c.sass)
    .pipe(p.plumber())
    .pipe(p.autoprefixer('last 4 version', '> 1%','ie 10', 'ie 9', 'ie 8', 'ie 7', 'Firefox ESR', 'Opera 12.1'))
    .pipe(p.sourcemaps.write('.'))
    .pipe(gulp.dest(c.dist.css));

    if (c.widgets) {
        p.rubySass(c.src.scssWidget + 'companyWidget.scss', c.sass)
        .pipe(p.plumber())
        .pipe(p.autoprefixer('last 4 version', '> 1%','ie 10', 'ie 9', 'ie 8', 'ie 7', 'Firefox ESR', 'Opera 12.1'))
        .pipe(p.sourcemaps.write('.'))
        .pipe(p.rename('dvhab-form-widget.css'))
        .pipe(gulp.dest(c.widget.dist.css));
    }
    if ( c.admin ) {
        p.rubySass(c.src.scssAdmin + 'admin.scss', c.sass)
        .pipe(p.plumber())
        .pipe(p.sourcemaps.write('.'))
        .pipe(gulp.dest(c.dist.cssAdmin));
    }
});
```

**Comment by robwierzbowski** [comment]
Can you find which sub-task is causing the errors, and give me the source and options?

**Comment by nikitabulatov** [comment]
```bash
[10:43:23] 'sprsrc/scss/viewdir/company.scss' was changed
[10:43:23] Starting 'scss'...
[10:43:23] Finished 'scss' after 12 ms
fs.js:849
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/tmp/gulp-ruby-sass-fd0d152d5598759dcdb787d86a419e37a7bc4cc9f2ecbde6d8fa7566e4f76c68/main.css'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at Immediate.<anonymous> (/Users/nb/www/catalog/node_modules/gulp-ruby-sass/index.js:148:12)
    at Immediate.immediate._onImmediate (timers.js:433:18)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by robwierzbowski** [comment]
It seems like there might be a problem generating the temporary directory. It's hard to debug when you have a complex task though. Can you reproduce the bug with a simple task like:

```
p.rubySass('main.scss')
.pipe(gulp.dest('dest/'))
```

**Comment by arasmussen** [comment]
+1

```
fs.js:892
  return binding.stat(pathModule._makeLong(path));
                                 ^

Error: ENOENT: no such file or directory, stat '/var/folders/l8/7vjf7c0n05g3gbpclc8tdcmr0000gn/T/gulp-ruby-sass-d7454e322ba7a72e63569ba3c9a054908f2bca12849936ddff5ce6309b1ac7cc/main.css'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at Immediate.<anonymous> (/Users/andrew/product-pains/node_modules/gulp-ruby-sass/index.js:148:12)
    at Immediate.immediate._onImmediate (timers.js:445:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by arasmussen** [comment]
Still getting this, three months later...

**Comment by robwierzbowski** [comment]
Unfortunately I haven't had much time to work on this module in the past few months. Pull requests accepted. 

I'm guessing that the issue is your environment does not have permissions to create the temporary directory.

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
