### ISSUE TITLE
Error: must provide pattern

### ISSUE THREAD

**Issue by jitendravyas** [sindresorhus/gulp-ruby-sass#288]
I'm using Ruby sass with PostCSS. This is my gulp css task.

```
gulp.task('css', function () {
    var processors = [
    short,
    rucksack,
    postcssmodules
    ];
    return gulp.src('./css/src/*.scss')
        .pipe(postcss(processors, {syntax: scss}))
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('./dest'));
});
```

Error I'm getting

```
➜  website git:(master) ✗ gulp css
[09:52:08] Using gulpfile ~/my-projects/website/gulpfile.js
[09:52:08] Starting 'css'...
[09:52:08] 'css' errored after 12 ms
[09:52:08] Error: must provide pattern
    at new GlobSync (/Users/jitendravyas/my-projects/website/node_modules/glob/sync.js:29:11)
    at Function.globSync [as sync] (/Users/jitendravyas/my-projects/website/node_modules/glob/sync.js:24:10)
    at /Users/jitendravyas/my-projects/website/node_modules/gulp-ruby-sass/index.js:68:21
    at Array.forEach (native)
    at gulpRubySass (/Users/jitendravyas/my-projects/website/node_modules/gulp-ruby-sass/index.js:67:10)
    at /Users/jitendravyas/my-projects/website/gulpfile.js:48:15
    at taskWrapper (/Users/jitendravyas/my-projects/website/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (/Users/jitendravyas/my-projects/website/node_modules/async-done/index.js:36:18)
```

**Comment by UltCombo** [comment]
GRS 1.x is now a gulp source adapter, see the [docs for upgrading](https://github.com/sindresorhus/gulp-ruby-sass#sasssource-options).

**Comment by jitendravyas** [comment]
I didn't get you. Do I need to change anything in my gulp script?

**Comment by kevva** [comment]
Yes, see the link @UltCombo provided. `gulp.src('./css/src/*.scss')` => `sass('./css/src/*.scss')`.
