### ISSUE TITLE
Compilation failure emit can't emit 

### ISSUE THREAD

**Issue by jpoikela** [sindresorhus/gulp-ruby-sass#289]
using {compass: true, and emitCompileError: true}
if I don't have compass installed the emit gives TypeError: this.emit is not a funciton

```
[11:13:57] ERROR: Cannot load compass.
[11:13:57] sass ERROR: Error in plugin 'gulp-ruby-sass'
Message:
    Sass compilation failed. See console output for more information.
Error in plugin 'gulp-ruby-sass'
Message:
    Sass compilation failed. See console output for more information.
/home/jpoikela/git/sevi-identification-ui/node_modules/gulp-ruby-sass/index.js:217
        this.emit('end');
             ^

TypeError: this.emit is not a function
    at Function.gulpRubySass.logError (/home/jpoikela/git/sevi-identification-ui/node_modules/gulp-ruby-sass/index.js:217:7)
    at Readable.sassError (/home/jpoikela/git/sevi-identification-ui/tasks/buildflowDev.js:73:8)
    at emitOne (events.js:77:13)
    at Readable.emit (events.js:169:7)
    at exports.emitErr (/home/jpoikela/git/sevi-identification-ui/node_modules/gulp-ruby-sass/lib/utils.js:9:9)
    at ChildProcess.<anonymous> (/home/jpoikela/git/sevi-identification-ui/node_modules/gulp-ruby-sass/index.js:150:4)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
```

**Comment by jpoikela** [comment]
user error
