### ISSUE TITLE
Unhandled error event 

### ISSUE THREAD

**Issue by jalvarado91** [sindresorhus/gulp-ruby-sass#37]
I seem to be having a problem with the gulp-ruby-sass, but there's not a lot of descriptive information on the output. 

```
$ gulp
[gulp] Using gulpfile /Users/jalvarado/Documents/Juan/jquery.cbFlyout/gulpfile.js
[gulp] Starting 'clean'...
[gulp] Finished 'clean' after 9.03 ms
[gulp] Starting 'default'...
[gulp] Starting 'styles'...
[gulp] Starting 'scripts'...
[gulp] Finished 'default' after 46 ms
[gulp] gulp-notify: [Gulp notification] Scripts task complete

events.js:72
        throw er; // Unhandled 'error' event
              ^
[gulp] Error in plugin 'gulp-ruby-sass': Exited with error code 1
    at ChildProcess.<anonymous> (/Users/jalvarado/Documents/Juan/jquery.cbFlyout/node_modules/gulp-ruby-sass/index.js:93:25)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

My gulpfile looks like this. 

```
var gulp = require('gulp'),
    sass = require('gulp-ruby-sass'),
    autoprefixer = require('gulp-autoprefixer'),
    minifycss = require('gulp-minify-css'),
    uglify = require('gulp-uglify'),
    rename = require('gulp-rename'),
    clean = require('gulp-clean'),
    concat = require('gulp-concat'),
    notify = require('gulp-notify'),
    cache = require('gulp-cache'),
    livereload = require('gulp-livereload'),
    lr = require('tiny-lr'),
    server = lr();

gulp.task('styles', function() {
  return gulp.src('scss/global.scss')
    .pipe(sass({ style: 'expanded', compass: true }))
    .pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
    .pipe(gulp.dest('css/'))
    .pipe(rename({suffix: '.min'}))
    .pipe(minifycss())
    .pipe(gulp.dest('css/'))
    .pipe(livereload(server))
    .pipe(notify({ message: 'Styles task complete' }));
});

gulp.task('scripts', function() {
  return gulp.src('js/src/*.js')
    .pipe(concat('main.js'))
    .pipe(gulp.dest('js/dist/'))
    .pipe(rename({suffix: '.min'}))
    .pipe(uglify())
    .pipe(gulp.dest('js/dist/'))
    .pipe(livereload(server))
    .pipe(notify({ message: 'Scripts task complete' }));
});

gulp.task('clean', function() {
  return gulp.src(['css/', 'js/dist/'], {read: false})
    .pipe(clean());
});

gulp.task('default', ['clean'], function() {
    gulp.start('styles', 'scripts');
});

gulp.task('watch', function() {
    // Listen on port 35729
  server.listen(35729, function (err) {
    if (err) {
      return console.log(err)
    };
        // Watch .scss files
        gulp.watch('scss/*.scss', ['styles']);

        // Watch .js files
        gulp.watch('js/src/*.js', ['scripts']);

    });
});``
```

Directory Structure

```
├── README.md
├── gulpfile.js
├── index.html
├── css
├── js
│   ├── dist
│   │   ├── main.js
│   │   └── main.min.js
│   └── src
│       ├── jquery.cbFlyout.js
│       ├── jquery.js
│       └── main.js
├── node_modules
├── package.json
└── scss
    └── global.scss
```

Any tips on what might be happening?

**Comment by danbower** [comment]
If anyone encounters this on their travels, old ruby-sass version was the cause of my error.

`gem update sass` to update :)

**Comment by zsitro** [comment]
@danbower neat

**Comment by mykz** [comment]
Cheers @danbower worked a treat!
